# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
permalink:           pretty

# Setup
url:                 https://seehearfeel.github.io/
paginate:            3

# Custom vars
version:             1.0.0

plugins:
  - jekyll-sitemap

plugins: [jekyll-paginate]
